blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/sotashimozono/QuasiCrystal.jl/discussions
    about: Use `Discussions` for questions and general discussions
